### ISSUE TITLE
why can't we access weights_C3D_sports1M_tf.h5? Can you please open it again?

### ISSUE THREAD

**Issue by ezzatmostafa96** [karolzak/conv3d-video-action-recognition#5]

**Comment by ezzatmostafa96** [comment]
Can you please upload the weights again :)

**Comment by karolzak** [comment]
Seems like links to my external storage have expired and I need to renew them. Thanks for pointing that out.

Here the link: [C3D weights](https://privdatastorage.blob.core.windows.net/github/video-action-recognition/weights_C3D_sports1M_tf.h5?sp=r&st=2021-06-08T08:50:24Z&se=2022-12-31T17:50:24Z&spr=https&sv=2020-02-10&sr=c&sig=4z4Qa3PL2U%2B6TQiNgkU1MF%2BUiNCcvCbvgGXeLBW9LLg%3D)
