### ISSUE TITLE
About feature extraction 

### ISSUE THREAD

**Issue by h1manshus1ngh** [karolzak/conv3d-video-action-recognition#7]
How do you had extracted the features

**Comment by karolzak** [comment]
I used C3D model to extract feature vectors.  
You can find the full pipeline used in this notebook: [https://github.com/karolzak/conv3d-video-action-recognition/blob/master/notebooks/kz-ucf101-action-recognition-with-c3d-svm.ipynb](https://github.com/karolzak/conv3d-video-action-recognition/blob/master/notebooks/kz-ucf101-action-recognition-with-c3d-svm.ipynb)
