### ISSUE TITLE
Import version for Tensorflow

### ISSUE THREAD

**Issue by shreyabhadwal** [karolzak/conv3d-video-action-recognition#8]
Hi Karol,

Is the repository built on Tensorflow version 1.something?
I am running the code on the latest Tensorflow versions and it's showing me some weird errors which are mostly related to versioning.

**Comment by karolzak** [comment]
Hi @shreyabhadwal 
Yes, this repo is 3 years old. Same goes for the code and all the dependencies

**Comment by shreyabhadwal** [comment]
Ahh
Thanks!
